### ISSUE TITLE
Crypto.js error

### ISSUE THREAD

**Issue by cwixon** [kundk-ckret/homebridge-lightify-api#1]
I'm trying this plugin for the first time and I get an error when starting up homebridge:

```
crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/uuid.js:14:11)
    at Lamp.Plug (/usr/local/lib/node_modules/homebridge-lightify-api/plug.js:7:38)
    at Lamp (/usr/local/lib/node_modules/homebridge-lightify-api/lamp.js:7:3)
    at /usr/local/lib/node_modules/homebridge-lightify-api/index.js:79:30
    at Array.forEach (native)
    at /usr/local/lib/node_modules/homebridge-lightify-api/index.js:73:14
    at ConnectManager.handleResponse (/usr/local/lib/node_modules/homebridge-lightify-api/node_modules/node-rest-client/lib/node-rest-client.js:448:5)
    at ConnectManager.handleEnd (/usr/local/lib/node_modules/homebridge-lightify-api/node_modules/node-rest-client/lib/node-rest-client.js:423:10)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-lightify-api/node_modules/node-rest-client/lib/node-rest-client.js:589:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Any ideas?  I think I have config.json set up correctly for this.  Here's what it looks like (in relevant portion):
```
        {
            "platform": "Lightify API",
            "name": "Lightify Cloud",
            "username": "email@domain.net",
            "password": "xxxxxxxx",
            "serialNumber": "OSR0xxxxxxx",
            "apiURL": "https://us.lightify-api.org/lightify/services/",
            "fadeTime": 3
        }
```

Thanks!  Looking forward to trying it.

**Comment by FamJohansson** [comment]
I got this error when i start homebridge after intalling this plugin.

[1/1/2017, 11:57:20 PM] ====================
[1/1/2017, 11:57:20 PM] ERROR LOADING PLUGIN homebridge-lightify-api:
[1/1/2017, 11:57:20 PM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)

**Comment by kundk-ckret** [comment]
Hi,

@FamJohansson - your nodeJS version is too old.
try to upgrade to a recent version.

@cwixon 
I'll have a look at this tomorrow :)

**Comment by kundk-ckret** [comment]
@cwixon - could you check your version of homebridge and its dependencies?
which versions do you use?

**Comment by cwixon** [comment]
Certainly!

nodejs 6.9.1
homebridge 0.4.16
homebridge-lightify-api 1.0.0
hap-nodejs 0.4.21
node-gyp 3.4.0

I'm running this in a docker container based on Debian Jessie.  Homebridge itself runs fine, as do some other plugins.

Thanks!

**Comment by kundk-ckret** [comment]
@cwixon could it be, that one of your lamps has no name set?
my code is trying to generate a UUID based on the item's name. It seems to crash there.

**Comment by FamJohansson** [comment]
All my lamps is named. 
I had installed nodejs v4.3.x. After uninstall this version and installed  7.4.0. and sudu -v returned 7.4.0. 

When starting homebridge it seems that there is som "leftovers" from v4.0.0.  How to completely remove all nodejs for all users?

**Comment by kundk-ckret** [comment]
what do you mean in detail with leftovers?

I'd try to remove the global npm packages and reinstall them:
npm uninstall -g homebridge homebridge-lightify-api && npm install -g homebridge homebridge-lightify-api

**Comment by cwixon** [comment]
@kundk-ckret aaaaaah, I think you may be right.  Earlier today I was fooling around with Home Assistant ([home-assistant.io](url)) and the Lightify support for that platform.  In addition to the bulbs I knew about -- and the ones listed in the Osram Lightify app -- there was one extra that Home Assistant called "unnamed device."  It was not visible in the Osram app and thus I couldn't control it or delete it.

That might very well explain what happened here, as well as the general unreliability of the Lightify system for me (many, many missed commands).  So I just did a factory reset and re-added all my bulbs (argh) and we'll see what happens.

I'll let you know what happens.  Maybe we can close this as a freak occurrence (or Osram bug).

**Comment by kundk-ckret** [comment]
@cwixon I added a check to ignore all devices with empty names now. So I think, your issue is now solved (as far as this plugin is involved ;) )

**Comment by kundk-ckret** [comment]
@FamJohansson your issue seems to be something different and to me it looks like, that its related to your nodejs installation and/or old node modules. 
Could you create a new issue if your problem persists?
