### ISSUE TITLE
Error: getaddrinfo ENOTFOUND us.lightify-api.org us.lightify-api.org:443

### ISSUE THREAD

**Issue by eds3028** [kundk-ckret/homebridge-lightify-api#11]
Error: getaddrinfo ENOTFOUND us.lightify-api.org us.lightify-api.org:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

I get this error when trying to initialise homebridge. No devices show up in my home kit app.

**Comment by drjamiwe** [comment]
I got exactly the same issue. Not sure whether the dev is still looking into it. Not sure if the API-Adress ist still the correct one used by Osram?

**Comment by kundk-ckret** [comment]
Hey guys, as i said before - I don't own any apple devices anymore so I can't test it...
It might be just a new API address but I think they changed something on the API itself too.

There are multiple alternatives to this package so migrating should be no problem.
