### ISSUE TITLE
not yet supported outside strict mode?

### ISSUE THREAD

**Issue by en2te** [kundk-ckret/homebridge-lightify-api#3]
Hi,
i get this error when starting homebridge. Other Plugins work fine. Where do i have to declare "strict mode"?

node -v is v4.2.1

ERROR LOADING PLUGIN homebridge-lightify-api:

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:128:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:51:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
[Mon Feb 06 2017 11:13:18 GMT+0100 (CET)]

**Comment by kundk-ckret** [comment]
Hello,

your node version is too old.
Please try to upgrade to a newer one.
