### ISSUE TITLE
error crash homebridge to exited

### ISSUE THREAD

**Issue by coniglioemanuele** [kundk-ckret/homebridge-lightify-api#4]
HI, 
here te log

     parser:
      HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': null,
        _headers: [],
        _url: '',
        _consumed: false,
        socket: [Object],
        incoming: null,
        outgoing: [Circular],
        maxHeaderPairs: 2000,
        onIncoming: [Function: parserOnIncomingClient] } } }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ENETUNREACH 52.28.225.160:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

sometimes it happend by few hour or by few days, i try to put the lightify address into the hosts file, supposing it was a dns error, but no help.
let me know if you need more information,

Thanks in advance

**Comment by kundk-ckret** [comment]
i think i need to add some errorhandling here
homebridge should not crash if the lightify server is not reachable

**Comment by kundk-ckret** [comment]
I improved the error handling now.
Please let me know if the error is fixed with version 1.1.0 which i release today.

**Comment by coniglioemanuele** [comment]
Just update to new release, i will keep monitored and let you know! appreciate the new options... export groups ;)

thanks

**Comment by coniglioemanuele** [comment]
Bad news, it worked for 16 hours and goes crash again
here the log

ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /lightify/services/session? HTTP/1.1\r\nContent-Type: application/json\r\nContent-Length: 92\r\nHost: eu.lightify-api.org\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/lightify/services/session?',
        _ended: false,
        _redirectable: [Circular],
        parser: [Object] },
     _currentUrl: 'https://eu.lightify-api.org' } }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND eu.lightify-api.org eu.lightify-api.org:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)


let ,me know if you need further info

thanks in advance

**Comment by kundk-ckret** [comment]
i think i need to simulate a network outage to reproduce this issue...
will have a look into this...

**Comment by coniglioemanuele** [comment]
ok, no problem, a this moment i use a work-aruond that restart the homebridge service to running state if it goes to exited
